In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns

In [ ]:
df = pd.read_csv("zomato_restaurants_in_India (2).csv")

In [ ]:
df.head(10)

,res_id,name,establishment,url,address,city,city_id,locality,latitude,longitude,...,price_range,currency,highlights,aggregate_rating,rating_text,votes,photo_count,opentable_support,delivery,takeaway
0,3400299,Bikanervala,['Quick Bites'],https://www.zomato.com/agra/bikanervala-khanda...,"Kalyani Point, Near Tulsi Cinema, Bypass Road,...",Agra,34,Khandari,27.211450,78.002381,...,2,Rs.,"['Lunch', 'Takeaway Available', 'Credit Card',...",4.4,Very Good,814,154,0.0,-1,-1
1,3400005,Mama Chicken Mama Franky House,['Quick Bites'],https://www.zomato.com/agra/mama-chicken-mama-...,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra,34,Agra Cantt,27.160569,78.011583,...,2,Rs.,"['Delivery', 'No Alcohol Available', 'Dinner',...",4.4,Very Good,1203,161,0.0,-1,-1
2,3401013,Bhagat Halwai,['Quick Bites'],https://www.zomato.com/agra/bhagat-halwai-2-sh...,"62/1, Near Easy Day, West Shivaji Nagar, Goalp...",Agra,34,Shahganj,27.182938,77.979684,...,1,Rs.,"['No Alcohol Available', 'Dinner', 'Takeaway A...",4.2,Very Good,801,107,0.0,1,-1
3,3400290,Bhagat Halwai,['Quick Bites'],https://www.zomato.com/agra/bhagat-halwai-civi...,"Near Anjana Cinema, Nehru Nagar, Civil Lines, ...",Agra,34,Civil Lines,27.205668,78.004799,...,1,Rs.,"['Takeaway Available', 'Credit Card', 'Lunch',...",4.3,Very Good,693,157,0.0,1,-1
4,3401744,The Salt Cafe Kitchen & Bar,['Casual Dining'],https://www.zomato.com/agra/the-salt-cafe-kitc...,"1C,3rd Floor, Fatehabad Road, Tajganj, Agra",Agra,34,Tajganj,27.157709,78.052421,...,3,Rs.,"['Lunch', 'Serves Alcohol', 'Cash', 'Credit Ca...",4.9,Excellent,470,291,0.0,1,-1
5,3400275,Domino's Pizza,['Quick Bites'],https://www.zomato.com/agra/dominos-pizza-civi...,"114/23 G, Deep Shikha Complex, Sanjay Place, C...",Agra,34,Civil Lines,27.201516,78.007556,...,2,Rs.,"['Credit Card', 'Lunch', 'Delivery', 'Dinner',...",4.0,Very Good,707,62,0.0,-1,-1
6,3400296,Honeydew Restaurant,['Quick Bites'],https://www.zomato.com/agra/honeydew-restauran...,"Opposite Soami Bagh Temple, Dayal Bagh, Agra",Agra,34,Dayal Bagh,27.222175,78.010174,...,2,Rs.,"['Dinner', 'Delivery', 'Lunch', 'Cash', 'Takea...",4.2,Very Good,647,46,0.0,1,-1
7,3400368,Domino's Pizza,['Quick Bites'],https://www.zomato.com/agra/dominos-pizza-sika...,"Plot C-1/6, Sector 13, Sikandra, Agra",Agra,34,Sikandra,27.203930,77.954260,...,2,Rs.,"['Lunch', 'Delivery', 'Credit Card', 'No Alcoh...",3.8,Good,617,18,0.0,-1,-1
8,3401284,Cake House,['Bakery'],https://www.zomato.com/agra/cake-house-2-civil...,"23/301, Wazirpura Rd, Judge Compound Chowraha,...",Agra,34,Civil Lines,27.204148,78.009025,...,2,Rs.,"['Takeaway Available', 'Cash', 'Indoor Seating...",3.4,Average,322,14,0.0,1,-1
9,3400838,Sugar N Thyme,['Café'],https://www.zomato.com/agra/sugar-n-thyme-tajg...,"1374 K/1375 K, Ground floor, Dinesh Nagar, Fat...",Agra,34,Tajganj,27.158243,78.045591,...,3,Rs.,"['No Alcohol Available', 'Dinner', 'Delivery',...",4.4,Very Good,289,324,0.0,1,-1

In [ ]:
df.city.nunique()

99

In [ ]:
df.city.unique()

array(['Agra', 'Ahmedabad', 'Gandhinagar', 'Ajmer', 'Alappuzha',
       'Allahabad', 'Amravati', 'Amritsar', 'Aurangabad', 'Bangalore',
       'Bhopal', 'Bhubaneshwar', 'Chandigarh', 'Mohali', 'Panchkula',
       'Zirakpur', 'Nayagaon', 'Chennai', 'Coimbatore', 'Cuttack',
       'Darjeeling', 'Dehradun', 'New Delhi', 'Gurgaon', 'Noida',
       'Faridabad', 'Ghaziabad', 'Greater Noida', 'Dharamshala',
       'Gangtok', 'Goa', 'Gorakhpur', 'Guntur', 'Guwahati', 'Gwalior',
       'Haridwar', 'Hyderabad', 'Secunderabad', 'Indore', 'Jabalpur',
       'Jaipur', 'Jalandhar', 'Jammu', 'Jamnagar', 'Jamshedpur', 'Jhansi',
       'Jodhpur', 'Junagadh', 'Kanpur', 'Kharagpur', 'Kochi', 'Kolhapur',
       'Kolkata', 'Howrah', 'Kota', 'Lucknow', 'Ludhiana', 'Madurai',
       'Manali', 'Mangalore', 'Manipal', 'Udupi', 'Meerut', 'Mumbai',
       'Thane', 'Navi Mumbai', 'Mussoorie', 'Mysore', 'Nagpur',
       'Nainital', 'Nasik', 'Nashik', 'Neemrana', 'Ooty', 'Palakkad',
       'Patiala', 'Patna', 'Puducherry', 'Pune', 'Pushkar', 'Raipur',
       'Rajkot', 'Ranchi', 'Rishikesh', 'Salem', 'Shimla', 'Siliguri',
       'Srinagar', 'Surat', 'Thrissur', 'Tirupati', 'Trichy',
       'Trivandrum', 'Udaipur', 'Varanasi', 'Vellore', 'Vijayawada',
       'Vizag', 'Vadodara'], dtype=object)

In [ ]:
df[df["city"]=="Pune"]

,res_id,name,establishment,url,address,city,city_id,locality,latitude,longitude,...,price_range,currency,highlights,aggregate_rating,rating_text,votes,photo_count,opentable_support,delivery,takeaway
164447,11283,Harajuku - The O Hotel,['Fine Dining'],https://www.zomato.com/pune/harajuku-the-o-hot...,"The O Hotel, North Main Road, Koregaon Park, Pune",Pune,5,"The O Hotel, Koregaon Park",18.540239,73.887518,...,4,Rs.,"['Cash', 'Debit Card', 'Lunch', 'Credit Card',...",3.7,Good,96,38,0.0,-1,-1
164448,10663,Mix@36 - The Westin,['Lounge'],https://www.zomato.com/pune/mix@36-the-westin-...,"The Westin, Survey 36/3B, KP Annexe Mundhwa Ro...",Pune,5,"The Westin, Mundhwa",18.540040,73.905910,...,4,Rs.,"['Cash', 'Debit Card', 'Serves Alcohol', 'Take...",4.0,Very Good,682,78,0.0,-1,-1
164449,10743,Kangan - The Westin,['Fine Dining'],https://www.zomato.com/pune/kangan-the-westin-...,"The Westin, 36/3B, KP Annexe, Mundhwa Road, Mu...",Pune,5,"The Westin, Mundhwa",18.539455,73.906040,...,4,Rs.,"['Serves Alcohol', 'Cash', 'Debit Card', 'Take...",4.0,Very Good,310,285,0.0,-1,-1
164450,18938162,Palette - The Westin,['Fine Dining'],https://www.zomato.com/pune/palette-the-westin...,"The Westin, 36/3B, KP Annexe, Mundhwa Road, Mu...",Pune,5,"The Westin, Mundhwa",18.539430,73.906009,...,4,Rs.,"['Serves Alcohol', 'Credit Card', 'Lunch', 'Ca...",3.3,Average,9,31,0.0,-1,-1
164451,18310167,Coriander Kitchen - Conrad Pune,['Fine Dining'],https://www.zomato.com/pune/coriander-kitchen-...,"Conrad, Mangaldas Road, Bund Garden Road, Pune",Pune,5,"Conrad Pune, Bund Garden Road",18.535409,73.883592,...,4,Rs.,"['Lunch', 'Serves Alcohol', 'Takeaway Availabl...",4.4,Very Good,500,1116,0.0,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168659,13061,Lonavla Restaurant & Bar- Hotel Lonavla,['Casual Dining'],https://www.zomato.com/pune/lonavla-restaurant...,"Gawlinaka, Mumbai-Pune Highway, Lonavala, Pune",Pune,5,Lonavala,18.754747,73.405682,...,3,Rs.,"['Dinner', 'Cash', 'Takeaway Available', 'Debi...",4.3,Very Good,474,81,0.0,-1,-1
168660,18555341,Utopia,['Casual Dining'],https://www.zomato.com/pune/utopia-lonavala?ut...,"CTS 159, Old Mumbai-Pune Road, Lonavala, Pune",Pune,5,Lonavala,18.754342,73.402737,...,3,Rs.,"['Dinner', 'Cash', 'Takeaway Available', 'Debi...",3.9,Good,336,204,0.0,-1,-1
168661,18767059,Mapro Garden,['Casual Dining'],https://www.zomato.com/pune/mapro-garden-lonav...,"3 & 4, Old Mumbai - Pune Highway, Valvan, Lona...",Pune,5,Lonavala,18.760234,73.419775,...,2,Rs.,"['Dinner', 'Takeaway Available', 'No Alcohol A...",4.3,Very Good,143,227,0.0,-1,-1
168662,6503906,Hotel Chandralok,['Casual Dining'],https://www.zomato.com/pune/hotel-chandralok-l...,"Near Bus Stand & Post Office, Opposite Mumbai-...",Pune,5,Lonavala,18.753223,73.405655,...,2,Rs.,"['No Alcohol Available', 'Dinner', 'Takeaway A...",4.3,Very Good,317,86,0.0,-1,-1
168663,18711838,Lion's Dhaaba,['Casual Dining'],https://www.zomato.com/pune/lions-dhaaba-6-lon...,"Besides Lion's Point, Ambey Valley, Atvan, Lon...",Pune,5,Lonavala,18.687172,73.393627,...,3,Rs.,"['Lunch', 'Takeaway Available', 'Dinner', 'Cas...",3.9,Good,67,171,0.0,-1,-1

In [ ]:

df[df["city"]=="Mumbai"]

,res_id,name,establishment,url,address,city,city_id,locality,latitude,longitude,...,price_range,currency,highlights,aggregate_rating,rating_text,votes,photo_count,opentable_support,delivery,takeaway
134852,18562340,Drinkery 51,['Casual Dining'],https://www.zomato.com/mumbai/drinkery-51-band...,"1st Floor, Vibgyor Towers, Bandra Kurla Comple...",Mumbai,3,Bandra Kurla Complex,19.067176,72.867493,...,4,Rs.,"['Dinner', 'Debit Card', 'Lunch', 'Serves Alco...",4.4,Very Good,3796,1897,0.0,1,-1
134853,34757,Joey's Pizza,['Quick Bites'],https://www.zomato.com/mumbai/joeys-pizza-mala...,"Shop 1, Plot D, Samruddhi Complex, Chincholi B...",Mumbai,3,Malad West,19.178188,72.834666,...,2,Rs.,"['Lunch', 'Cash', 'Takeaway Available', 'Debit...",4.5,Excellent,7932,4960,0.0,-1,-1
134854,18548172,Hitchki,['Bar'],https://www.zomato.com/mumbai/hitchki-powai?ut...,"5, Transocean, Hiranandani Business Park, Lake...",Mumbai,3,Powai,19.119930,72.907331,...,3,Rs.,"['Lunch', 'Serves Alcohol', 'Cash', 'Credit Ca...",4.7,Excellent,3762,12979,0.0,1,-1
134855,18392725,Tamasha,['Lounge'],https://www.zomato.com/mumbai/tamasha-lower-pa...,"Ground Floor, Victoria House, E.B Marg, Lower ...",Mumbai,3,Lower Parel,19.006060,72.827496,...,4,Rs.,"['Dinner', 'Cash', 'Takeaway Available', 'Cred...",4.7,Excellent,4979,16595,0.0,-1,-1
134856,18962112,Bayroute,['Fine Dining'],https://www.zomato.com/mumbai/bayroute-juhu?ut...,"14, Silver Beach Estate, A.B. Nair Road, Oppos...",Mumbai,3,Juhu,19.110684,72.825368,...,4,Rs.,"['Dinner', 'Cash', 'Takeaway Available', 'Debi...",4.9,Excellent,706,2484,0.0,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142348,46792,BOX8- Desi Meals,[],https://www.zomato.com/mumbai/box8-desi-meals-...,"102, Bhavani Industrial Estate, Opposite IIT B...",Mumbai,3,Powai,19.124284,72.914877,...,1,Rs.,"['Cash', 'Debit Card', 'Takeaway Available', '...",4.0,Very Good,726,703,0.0,1,-1
142349,37750,Faasos,['Quick Bites'],https://www.zomato.com/mumbai/faasos-veera-des...,"Shop 06, Building 2, Pramukh Park Rehab CHS Li...",Mumbai,3,Veera Desai Area,19.139601,72.833119,...,1,Rs.,"['Dinner', 'Cash', 'Takeaway Available', 'Debi...",3.9,Good,510,251,0.0,1,-1
142350,18165909,Charcoal Eats Express,['Quick Bites'],https://www.zomato.com/mumbai/charcoal-eats-ex...,"Opposite Kamala Mills, Lower Parel, Mumbai",Mumbai,3,Lower Parel,19.002537,72.829391,...,2,Rs.,"['Lunch', 'Cash', 'Credit Card', 'Dinner', 'St...",4.0,Very Good,491,344,0.0,-1,-1
142351,18306481,Wok Express,['Food Court'],https://www.zomato.com/mumbai/wok-express-1-an...,"Food Court, 2nd Floor, Infinity Mall, Unit 215...",Mumbai,3,"Infiniti Mall, Andheri Lokhandwala, Andheri West",19.141117,72.831181,...,2,Rs.,"['No Alcohol Available', 'Dinner', 'Mall Parki...",3.7,Good,515,490,0.0,-1,-1
142352,18140577,Rasoi Thali,['Quick Bites'],https://www.zomato.com/mumbai/rasoi-thali-mulu...,"Shop 5, Bhodke Building, Near Hanuman Mandir, ...",Mumbai,3,Mulund West,19.172657,72.956466,...,1,Rs.,"['Lunch', 'Cash', 'Debit Card', 'Dinner', 'Tak...",3.9,Good,142,34,0.0,-1,-1

In [ ]:
df[df["city"]=="Agra"]

,res_id,name,establishment,url,address,city,city_id,locality,latitude,longitude,...,price_range,currency,highlights,aggregate_rating,rating_text,votes,photo_count,opentable_support,delivery,takeaway
0,3400299,Bikanervala,['Quick Bites'],https://www.zomato.com/agra/bikanervala-khanda...,"Kalyani Point, Near Tulsi Cinema, Bypass Road,...",Agra,34,Khandari,27.211450,78.002381,...,2,Rs.,"['Lunch', 'Takeaway Available', 'Credit Card',...",4.4,Very Good,814,154,0.0,-1,-1
1,3400005,Mama Chicken Mama Franky House,['Quick Bites'],https://www.zomato.com/agra/mama-chicken-mama-...,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra,34,Agra Cantt,27.160569,78.011583,...,2,Rs.,"['Delivery', 'No Alcohol Available', 'Dinner',...",4.4,Very Good,1203,161,0.0,-1,-1
2,3401013,Bhagat Halwai,['Quick Bites'],https://www.zomato.com/agra/bhagat-halwai-2-sh...,"62/1, Near Easy Day, West Shivaji Nagar, Goalp...",Agra,34,Shahganj,27.182938,77.979684,...,1,Rs.,"['No Alcohol Available', 'Dinner', 'Takeaway A...",4.2,Very Good,801,107,0.0,1,-1
3,3400290,Bhagat Halwai,['Quick Bites'],https://www.zomato.com/agra/bhagat-halwai-civi...,"Near Anjana Cinema, Nehru Nagar, Civil Lines, ...",Agra,34,Civil Lines,27.205668,78.004799,...,1,Rs.,"['Takeaway Available', 'Credit Card', 'Lunch',...",4.3,Very Good,693,157,0.0,1,-1
4,3401744,The Salt Cafe Kitchen & Bar,['Casual Dining'],https://www.zomato.com/agra/the-salt-cafe-kitc...,"1C,3rd Floor, Fatehabad Road, Tajganj, Agra",Agra,34,Tajganj,27.157709,78.052421,...,3,Rs.,"['Lunch', 'Serves Alcohol', 'Cash', 'Credit Ca...",4.9,Excellent,470,291,0.0,1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2617,3400025,Jahanpanah,['Casual Dining'],https://www.zomato.com/agra/jahanpanah-agra-ca...,"E 23, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra,34,Agra Cantt,27.161661,78.011544,...,3,Rs.,"['Dinner', 'Cash', 'Delivery', 'Lunch', 'Takea...",3.8,Good,288,266,0.0,1,-1
2618,3400346,Sheroes Hangout,['Café'],https://www.zomato.com/agra/sheroes-hangout-ta...,"R.K.Puram Phase 2, Tajnagri, Agra",Agra,34,Tajganj,27.160417,78.053800,...,1,Rs.,"['No Alcohol Available', 'Dinner', 'Cash', 'De...",4.8,Excellent,262,220,0.0,-1,-1
2619,3400263,Rambabu Parantha Bhandar,['Casual Dining'],https://www.zomato.com/agra/rambabu-parantha-b...,"6/127, Belanganj, Civil Lines, Agra",Agra,34,Civil Lines,27.191576,78.023651,...,2,Rs.,"['Dinner', 'Takeaway Available', 'Lunch', 'Cas...",3.8,Good,326,45,0.0,-1,-1
2620,3400019,Dasaprakash Restaurant,['Casual Dining'],https://www.zomato.com/agra/dasaprakash-restau...,"Meher Cinema Complex, Gwalior Road, Rakabganj,...",Agra,34,Rakabganj,27.165024,78.014914,...,2,Rs.,"['Credit Card', 'Lunch', 'Debit Card', 'Dinner...",4.1,Very Good,225,100,0.0,1,-1
2621,3400107,Esphahan - The Oberoi Amarvilas,['Fine Dining'],https://www.zomato.com/agra/esphahan-the-obero...,"The Oberoi Amarvilas, Taj East Gate Road, Fate...",Agra,34,"The Oberoi Amarvilas, Tajganj",27.168148,78.048732,...,4,Rs.,"['Dinner', 'Cash', 'Credit Card', 'Serves Alco...",4.1,Very Good,36,49,0.0,-1,-1

In [ ]:
df.shape

(211944, 26)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211944 entries, 0 to 211943
Data columns (total 26 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   res_id                211944 non-null  int64
 1   name                  211944 non-null  object
 2   establishment         211944 non-null  object
 3   url                   211944 non-null  object
 4   address               211810 non-null  object
 5   city                  211944 non-null  object
 6   city_id               211944 non-null  int64
 7   locality              211944 non-null  object
 8   latitude              211944 non-null  float64
 9   longitude             211944 non-null  float64
 10  zipcode               48757 non-null   object
 11  country_id            211944 non-null  int64
 12  locality_verbose      211944 non-null  object
 13  cuisines              210553 non-null  object
 14  timings               208070 non-null  object
 15  average_cost_for_two  211944 non-null  int64
 16  price_range           211944 non-null  int64
 17  currency              211944 non-null  object
 18  highlights            211944 non-null  object
 19  aggregate_rating      211944 non-null  float64
 20  rating_text           211944 non-null  object
 21  votes                 211944 non-null  int64
 22  photo_count           211944 non-null  int64
 23  opentable_support     211896 non-null  float64
 24  delivery              211944 non-null  int64
 25  takeaway              211944 non-null  int64
dtypes: float64(4), int64(9), object(13)
memory usage: 42.0+ MB

In [ ]:
df.describe()

,res_id,city_id,latitude,longitude,country_id,average_cost_for_two,price_range,aggregate_rating,votes,photo_count,opentable_support,delivery,takeaway
count,2.119440e+05,211944.000000,211944.000000,211944.000000,211944.0,211944.000000,211944.000000,211944.000000,211944.000000,211944.000000,211896.0,211944.000000,211944.0
mean,1.349411e+07,4746.785434,21.499758,77.615276,1.0,595.812229,1.882535,3.395937,378.001864,256.971224,0.0,-0.255907,-1.0
std,7.883722e+06,5568.766386,22.781331,7.500104,0.0,606.239363,0.892989,1.283642,925.333370,867.668940,0.0,0.964172,0.0
min,5.000000e+01,1.000000,0.000000,0.000000,1.0,0.000000,1.000000,0.000000,-18.000000,0.000000,0.0,-1.000000,-1.0
25%,3.301027e+06,11.000000,15.496071,74.877961,1.0,250.000000,1.000000,3.300000,16.000000,3.000000,0.0,-1.000000,-1.0
50%,1.869573e+07,34.000000,22.514494,77.425971,1.0,400.000000,2.000000,3.800000,100.000000,18.000000,0.0,-1.000000,-1.0
75%,1.881297e+07,11306.000000,26.841667,80.219323,1.0,700.000000,2.000000,4.100000,362.000000,128.000000,0.0,1.000000,-1.0
max,1.915979e+07,11354.000000,10000.000000,91.832769,1.0,30000.000000,4.000000,4.900000,42539.000000,17702.000000,0.0,1.000000,-1.0

In [ ]:
df[df["average_cost_for_two"]==10000]

,res_id,name,establishment,url,address,city,city_id,locality,latitude,longitude,...,price_range,currency,highlights,aggregate_rating,rating_text,votes,photo_count,opentable_support,delivery,takeaway
135918,38945,Wasabi By Morimoto - The Taj Mahal Palace,['Fine Dining'],https://www.zomato.com/mumbai/wasabi-by-morimo...,"The Taj Mahal Palace & Tower, Apollo Bunder, C...",Mumbai,3,"The Taj Mahal Palace, Colaba",18.92214,72.833756,...,4,Rs.,"['Dinner', 'Cash', 'Credit Card', 'Lunch', 'De...",4.3,Very Good,616,634,0.0,-1,-1
136241,38945,Wasabi By Morimoto - The Taj Mahal Palace,['Fine Dining'],https://www.zomato.com/mumbai/wasabi-by-morimo...,"The Taj Mahal Palace & Tower, Apollo Bunder, C...",Mumbai,3,"The Taj Mahal Palace, Colaba",18.92214,72.833756,...,4,Rs.,"['Dinner', 'Cash', 'Credit Card', 'Lunch', 'De...",4.3,Very Good,616,634,0.0,-1,-1
136741,38945,Wasabi By Morimoto - The Taj Mahal Palace,['Fine Dining'],https://www.zomato.com/mumbai/wasabi-by-morimo...,"The Taj Mahal Palace & Tower, Apollo Bunder, C...",Mumbai,3,"The Taj Mahal Palace, Colaba",18.92214,72.833756,...,4,Rs.,"['Dinner', 'Cash', 'Credit Card', 'Lunch', 'De...",4.3,Very Good,616,634,0.0,-1,-1
137241,38945,Wasabi By Morimoto - The Taj Mahal Palace,['Fine Dining'],https://www.zomato.com/mumbai/wasabi-by-morimo...,"The Taj Mahal Palace & Tower, Apollo Bunder, C...",Mumbai,3,"The Taj Mahal Palace, Colaba",18.92214,72.833756,...,4,Rs.,"['Dinner', 'Cash', 'Credit Card', 'Lunch', 'De...",4.3,Very Good,616,634,0.0,-1,-1
138607,38945,Wasabi By Morimoto - The Taj Mahal Palace,['Fine Dining'],https://www.zomato.com/mumbai/wasabi-by-morimo...,"The Taj Mahal Palace & Tower, Apollo Bunder, C...",Mumbai,3,"The Taj Mahal Palace, Colaba",18.92214,72.833756,...,4,Rs.,"['Dinner', 'Cash', 'Credit Card', 'Lunch', 'De...",4.3,Very Good,616,634,0.0,-1,-1

In [ ]:
df.drop_duplicates(["res_id"], keep = 'first' , inplace = True)

In [ ]:
df.shape

(55568, 26)

In [ ]:
df.isnull().sum()

res_id                      0
name                        0
establishment               0
url                         0
address                    18
city                        0
city_id                     0
locality                    0
latitude                    0
longitude                   0
zipcode                 44623
country_id                  0
locality_verbose            0
cuisines                  470
timings                  1003
average_cost_for_two        0
price_range                 0
currency                    0
highlights                  0
aggregate_rating            0
rating_text                 0
votes                       0
photo_count                 0
opentable_support          12
delivery                    0
takeaway                    0
dtype: int64

In [ ]:
df["establishment"].unique()

array(["['Quick Bites']", "['Casual Dining']", "['Bakery']", "['Café']",
       "['Dhaba']", "['Bhojanalya']", "['Bar']", "['Sweet Shop']",
       "['Fine Dining']", "['Food Truck']", "['Dessert Parlour']",
       "['Lounge']", "['Pub']", "['Beverage Shop']", "['Kiosk']",
       "['Paan Shop']", "['Confectionery']", '[]', "['Shack']",
       "['Club']", "['Food Court']", "['Mess']", "['Butcher Shop']",
       "['Microbrewery']", "['Cocktail Bar']", "['Pop up']",
       "['Irani Cafe']"], dtype=object)

In [ ]:
print(df["establishment"].unique()[0])
print(type(df["establishment"].unique()[0]))

['Quick Bites']
<class 'str'>

In [ ]:
print(df["establishment"].unique())

["['Quick Bites']" "['Casual Dining']" "['Bakery']" "['Café']" "['Dhaba']"
 "['Bhojanalya']" "['Bar']" "['Sweet Shop']" "['Fine Dining']"
 "['Food Truck']" "['Dessert Parlour']" "['Lounge']" "['Pub']"
 "['Beverage Shop']" "['Kiosk']" "['Paan Shop']" "['Confectionery']" '[]'
 "['Shack']" "['Club']" "['Food Court']" "['Mess']" "['Butcher Shop']"
 "['Microbrewery']" "['Cocktail Bar']" "['Pop up']" "['Irani Cafe']"]

In [ ]:
df["establishment"] = df["establishment"].apply(lambda x:x[2:-2])
print(df["establishment"].unique())

['Quick Bites' 'Casual Dining' 'Bakery' 'Café' 'Dhaba' 'Bhojanalya' 'Bar'
 'Sweet Shop' 'Fine Dining' 'Food Truck' 'Dessert Parlour' 'Lounge' 'Pub'
 'Beverage Shop' 'Kiosk' 'Paan Shop' 'Confectionery' '' 'Shack' 'Club'
 'Food Court' 'Mess' 'Butcher Shop' 'Microbrewery' 'Cocktail Bar' 'Pop up'
 'Irani Cafe']

In [ ]:
len(df.city.unique())

99

In [ ]:
df['city'].unique()

array(['Agra', 'Ahmedabad', 'Gandhinagar', 'Ajmer', 'Alappuzha',
       'Allahabad', 'Amravati', 'Amritsar', 'Aurangabad', 'Bangalore',
       'Bhopal', 'Bhubaneshwar', 'Chandigarh', 'Mohali', 'Panchkula',
       'Zirakpur', 'Nayagaon', 'Chennai', 'Coimbatore', 'Cuttack',
       'Darjeeling', 'Dehradun', 'New Delhi', 'Gurgaon', 'Noida',
       'Faridabad', 'Ghaziabad', 'Greater Noida', 'Dharamshala',
       'Gangtok', 'Goa', 'Gorakhpur', 'Guntur', 'Guwahati', 'Gwalior',
       'Haridwar', 'Hyderabad', 'Secunderabad', 'Indore', 'Jabalpur',
       'Jaipur', 'Jalandhar', 'Jammu', 'Jamnagar', 'Jamshedpur', 'Jhansi',
       'Jodhpur', 'Junagadh', 'Kanpur', 'Kharagpur', 'Kochi', 'Kolhapur',
       'Kolkata', 'Howrah', 'Kota', 'Lucknow', 'Ludhiana', 'Madurai',
       'Manali', 'Mangalore', 'Manipal', 'Udupi', 'Meerut', 'Mumbai',
       'Thane', 'Navi Mumbai', 'Mussoorie', 'Mysore', 'Nagpur',
       'Nainital', 'Nasik', 'Nashik', 'Neemrana', 'Ooty', 'Palakkad',
       'Patiala', 'Patna', 'Puducherry', 'Pune', 'Pushkar', 'Raipur',
       'Rajkot', 'Ranchi', 'Rishikesh', 'Salem', 'Shimla', 'Siliguri',
       'Srinagar', 'Surat', 'Thrissur', 'Tirupati', 'Trichy',
       'Trivandrum', 'Udaipur', 'Varanasi', 'Vellore', 'Vijayawada',
       'Vizag', 'Vadodara'], dtype=object)

In [ ]:
df["country_id"].nunique()

1

In [ ]:
print(df["cuisines"].nunique())

9382

In [ ]:
print(df["cuisines"].unique())

['North Indian, South Indian, Mithai, Street Food, Desserts'
 'North Indian, Mughlai, Rolls, Chinese, Fast Food, Street Food'
 'Fast Food, Mithai' ...
 'Street Food, Biryani, Chinese, Fast Food, North Indian, Mughlai'
 'North Indian, Chinese, Mexican, Italian, Thai, Continental'
 'North Indian, Lucknowi, Chinese']

In [ ]:
df["cuisines"]=df["cuisines"].fillna("No cuisines")
df["cuisines"].nunique()

9383

In [ ]:
cuisines = []
df["cuisines"].apply(lambda x : cuisines.extend(x.split(", ")))
cuisines  = pd.Series(cuisines)
print("Total number of unique cuisines = ", cuisines.nunique())

Total number of unique cuisines =  134

In [ ]:
df["average_cost_for_two"].nunique()

145

In [ ]:
df["aggregate_rating"].unique()

array([4.4, 4.2, 4.3, 4.9, 4. , 3.8, 3.4, 4.1, 3.5, 4.6, 3.9, 3.6, 4.5,
       4.7, 3.7, 4.8, 3.2, 0. , 3.3, 2.8, 3.1, 2.6, 3. , 2.7, 2.9, 2.2,
       2.3, 2.4, 2.5, 2.1, 1.8, 2. , 1.9])

In [ ]:
df.drop(['url','city_id','locality','latitude','longitude','zipcode','country_id','locality_verbose','timings','price_range','currency','highlights','rating_text','votes','photo_count'],axis = 1 , inplace = True)

In [ ]:
df.head()

,res_id,name,establishment,address,city,cuisines,average_cost_for_two,aggregate_rating,opentable_support,delivery,takeaway
0,3400299,Bikanervala,Quick Bites,"Kalyani Point, Near Tulsi Cinema, Bypass Road,...",Agra,"North Indian, South Indian, Mithai, Street Foo...",700,4.4,0.0,-1,-1
1,3400005,Mama Chicken Mama Franky House,Quick Bites,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra,"North Indian, Mughlai, Rolls, Chinese, Fast Fo...",600,4.4,0.0,-1,-1
2,3401013,Bhagat Halwai,Quick Bites,"62/1, Near Easy Day, West Shivaji Nagar, Goalp...",Agra,"Fast Food, Mithai",300,4.2,0.0,1,-1
3,3400290,Bhagat Halwai,Quick Bites,"Near Anjana Cinema, Nehru Nagar, Civil Lines, ...",Agra,"Desserts, Bakery, Fast Food, South Indian",300,4.3,0.0,1,-1
4,3401744,The Salt Cafe Kitchen & Bar,Casual Dining,"1C,3rd Floor, Fatehabad Road, Tajganj, Agra",Agra,"North Indian, Continental, Italian",1000,4.9,0.0,1,-1

In [ ]:
df.drop(['opentable_support','delivery','takeaway'],axis = 1,inplace = True)

In [ ]:
df.head()

,res_id,name,establishment,address,city,cuisines,average_cost_for_two,aggregate_rating
0,3400299,Bikanervala,Quick Bites,"Kalyani Point, Near Tulsi Cinema, Bypass Road,...",Agra,"North Indian, South Indian, Mithai, Street Foo...",700,4.4
1,3400005,Mama Chicken Mama Franky House,Quick Bites,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra,"North Indian, Mughlai, Rolls, Chinese, Fast Fo...",600,4.4
2,3401013,Bhagat Halwai,Quick Bites,"62/1, Near Easy Day, West Shivaji Nagar, Goalp...",Agra,"Fast Food, Mithai",300,4.2
3,3400290,Bhagat Halwai,Quick Bites,"Near Anjana Cinema, Nehru Nagar, Civil Lines, ...",Agra,"Desserts, Bakery, Fast Food, South Indian",300,4.3
4,3401744,The Salt Cafe Kitchen & Bar,Casual Dining,"1C,3rd Floor, Fatehabad Road, Tajganj, Agra",Agra,"North Indian, Continental, Italian",1000,4.9

In [ ]:
df_new = df.dropna(axis=0)
df_new

,res_id,name,establishment,address,city,cuisines,average_cost_for_two,aggregate_rating
0,3400299,Bikanervala,Quick Bites,"Kalyani Point, Near Tulsi Cinema, Bypass Road,...",Agra,"North Indian, South Indian, Mithai, Street Foo...",700,4.4
1,3400005,Mama Chicken Mama Franky House,Quick Bites,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra,"North Indian, Mughlai, Rolls, Chinese, Fast Fo...",600,4.4
2,3401013,Bhagat Halwai,Quick Bites,"62/1, Near Easy Day, West Shivaji Nagar, Goalp...",Agra,"Fast Food, Mithai",300,4.2
3,3400290,Bhagat Halwai,Quick Bites,"Near Anjana Cinema, Nehru Nagar, Civil Lines, ...",Agra,"Desserts, Bakery, Fast Food, South Indian",300,4.3
4,3401744,The Salt Cafe Kitchen & Bar,Casual Dining,"1C,3rd Floor, Fatehabad Road, Tajganj, Agra",Agra,"North Indian, Continental, Italian",1000,4.9
...,...,...,...,...,...,...,...,...
211882,19142822,Shree Janta Ice Cream,Dessert Parlour,"Ground Floor, 5 Ronak Plaza, Tulsidham Char Ra...",Vadodara,Ice Cream,200,2.9
211925,18984164,The Grand Thakar,Casual Dining,"3rd Floor, Shreem Shalini Mall, Opposite Conqu...",Vadodara,"Gujarati, North Indian, Chinese",700,4.0
211926,18019952,Geeta lodge,Casual Dining,"Shop 11, Ground Floor, Atlantis K-10, Tower A,...",Vadodara,"Gujarati, Street Food",250,3.9
211940,3200996,Raju Omlet,Quick Bites,"Mahalaxmi Apartment, Opposite B O B, Karoli Ba...",Vadodara,Fast Food,300,4.1
211942,3201138,Subway,Quick Bites,"G-2, Vedant Platina, Near Cosmos, Akota, Vadodara",Vadodara,"Fast Food, Sandwich, Salad",500,3.7

In [ ]:
df_new.isna().sum()

res_id                  0
name                    0
establishment           0
address                 0
city                    0
cuisines                0
average_cost_for_two    0
aggregate_rating        0
dtype: int64

In [ ]:
# Combine relevant columns for content-based features
df_new['combined_features'] = (df_new['cuisines'] + ' ' + df_new['name'] + ' ' + df_new['address'] + ' ' + df_new['city']).str.lower()

<ipython-input-51-787d3389a275>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['combined_features'] = (df_new['cuisines'] + ' ' + df_new['name'] + ' ' + df_new['address'] + ' ' + df_new['city']).str.lower()

In [ ]:
# Initialize TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD


tfidf = TfidfVectorizer(stop_words='english')

In [ ]:
# Create the TF-IDF matrix
tfidf_matrix = tfidf.fit_transform(df_new['combined_features'])

In [ ]:
from sklearn.neighbors import NearestNeighbors

# Fit NearestNeighbors model
knn = NearestNeighbors(metric='cosine', algorithm='brute')
knn.fit(tfidf_matrix)

# Find top 10 neighbors for each row
distances, indices = knn.kneighbors(tfidf_matrix, n_neighbors=10)

In [111]:
print(tfidf_matrix.shape)

(55550, 42645)

In [112]:




df_new.columns

Index(['res_id', 'name', 'establishment', 'address', 'city', 'cuisines',
       'average_cost_for_two', 'aggregate_rating', 'combined_features'],
      dtype='object')

In [113]:
print(df_new['res_id'].unique())

[ 3400299  3400005  3401013 ... 18019952  3200996  3201138]

In [114]:
idx = df_new[df_new['res_id'] == 3400299].index[0]  # Use a valid restaurant ID
print("Neighbor Indices for restaurant 3400299:", indices[idx])
print("Neighbor Distances for restaurant 3400299:", distances[idx])

Neighbor Indices for restaurant 3400299: [  0 319 388 423 707  68  11 595 315  72 634  89 198 176 632 341 692 421
 294 371]
Neighbor Distances for restaurant 3400299: [0.         0.42450409 0.48155354 0.51590331 0.53189594 0.53455635
 0.53730012 0.57791837 0.57880767 0.59697619 0.59793604 0.59815184
 0.60118083 0.60516859 0.60758275 0.62050373 0.62154822 0.62202736
 0.62759073 0.63255147]

In [115]:
# Test the recommendation without filters
recommended = recommend_restaurants_knn(
    restaurant_id=3400299,  # Replace with the valid restaurant ID
    num_recommendations=10,
    city=None,  # No city filter
    min_cost=None,  # No cost filter
    max_cost=None,  # No cost filter
    cuisine=None  # No cuisine filter

)





print("Recommended Restaurants without any filters:")
print(recommended)

Recommended Restaurants without any filters:
                          name  \
319       Bulaki Non Veg Point
388                 Roots Cafe
423                Sagar Ratna
707        Agarwal Sweet House
68                      G Thal
11                 Bikanervala
595  chhabra bake house & cafe
315           Saket Restaurant
72             Udupi Brindavan
634      New Vishal Restaurant

                                               address  \
319    Near Tulsi Talkies, Bypass Road, Khandari, Agra
388  321, Mayur Complex, Bypass Road, Near Tulsi Ta...
423      821, Khandari Crossing, N H 2, Khandari, Agra
707                           Shop 6/5, Khandari, Agra
68   3/20, KPS Tower, Near Tulsi Talkies, Bypass Ro...
11   Opposite ITC Mughal, Fatehbad Road, Tajganj, Agra
595    2/91, Kotla house Khandari Agra, Khandari, Agra
315  75-76, Saket Mall, Gandhi Nagar, Bypass Road, ...
72   India House, Near A1 Hospital, Nehru Nagar, Kh...
634  531, M G Road , Bhagwan Talkies Crossing, Khan...

                                              cuisines  average_cost_for_two  \
319                                       North Indian                   500
388                            North Indian, Fast Food                   200
423  South Indian, North Indian, Street Food, Chine...                   600
707                                             Mithai                   300
68                       Rajasthani, Gujarati, Mughlai                   900
11   North Indian, South Indian, Mithai, Street Foo...                   700
595                                               Cafe                   200
315                North Indian, Chinese, South Indian                   750
72                 South Indian, North Indian, Chinese                   600
634                     North Indian, Desserts, Mithai                   400

     aggregate_rating
319               2.7
388               2.9
423               3.5
707               0.0
68                3.7
11                4.4
595               0.0
315               2.7
72                4.2
634               3.6

In [137]:
# Clean and normalize the 'cuisines' column (lowercase, remove extra spaces)
df_new['cuisines'] = df_new['cuisines'].str.lower().str.replace(r'\s+', ' ', regex=True).str.strip()

def recommend_restaurants_knn(restaurant_id, num_recommendations=10, city=None, min_cost=None, max_cost=None, cuisine=None):
    try:
        # Get the index of the given restaurant
        idx = df_new[df_new['res_id'] == restaurant_id].index[0]

        # Get the indices of the nearest neighbors, excluding the restaurant itself
        neighbor_indices = indices[idx][1:]  # Exclude the first index (self)

        # Create a dataframe with the neighbor restaurants
        neighbors_df = df_new.iloc[neighbor_indices].copy()

        # Apply city filter
        if city:
            neighbors_df = neighbors_df[neighbors_df['city'].str.lower() == city.lower()]
            print("After city filter:", neighbors_df.shape)

        # Apply cost filters
        if min_cost is not None:
            neighbors_df = neighbors_df[neighbors_df['average_cost_for_two'] >= min_cost]
            print("After min cost filter:", neighbors_df.shape)

        if max_cost is not None:
            neighbors_df = neighbors_df[neighbors_df['average_cost_for_two'] <= max_cost]
            print("After max cost filter:", neighbors_df.shape)

        # Apply cuisine filter
        if cuisine:
            # Normalize the cuisine input to a list
            cuisine_list = [c.strip().lower() for c in cuisine.split(",")] if isinstance(cuisine, str) else cuisine
            neighbors_df = neighbors_df[
                neighbors_df['cuisines'].apply(lambda x: any(c in x for c in cuisine_list) if isinstance(x, str) else False)
            ]
            print("After cuisine filter:", neighbors_df.shape)

        # Check if any restaurants remain after filtering
        if neighbors_df.empty:
            print("No recommendations found after applying filters.")
            return None

        # Select top N recommended restaurants
        neighbors_df = neighbors_df.head(num_recommendations)

        # Return the recommended restaurants' details
        return neighbors_df[['name', 'address', 'cuisines', 'average_cost_for_two', 'aggregate_rating']]

    except IndexError:
        print(f"Restaurant ID {restaurant_id} not found in the dataset.")
        return None
    except Exception as e:
        print("An error occurred:", str(e))
        return None

# Example test
recommended = recommend_restaurants_knn(
    restaurant_id=3400299,  # Replace with the valid restaurant ID
    num_recommendations=10,
    city="Agra",  # Apply city filter
    min_cost=500,  # Apply less restrictive cost filter
    max_cost=5000,  # Apply less restrictive cost filter
    cuisine="chinese"  # Filter for multiple cuisines
)

print("Recommended Restaurants:")
print(recommended)

After city filter: (19, 9)
After min cost filter: (9, 9)
After max cost filter: (9, 9)
After cuisine filter: (5, 9)
Recommended Restaurants:
                                  name  \
656                        Sagar Ratna
414                   Saket Restaurant
72                     Udupi Brindavan
193                          Big Daddy
654  Brijwasi Sweet House & Restaurant

                                               address  \
656      821, Khandari Crossing, N H 2, Khandari, Agra
414  75-76, Saket Mall, Gandhi Nagar, Bypass Road, ...
72   India House, Near A1 Hospital, Nehru Nagar, Kh...
193   Above Bikanervala, Fatehabad Road, Tajganj, Agra
654  D 2, Shopping Arcade, Sadar Bazaar, Agra Cantt...

                                              cuisines  average_cost_for_two  \
656  south indian, north indian, street food, chine...                   600
414                north indian, chinese, south indian                   750
72                 south indian, north indian, chinese                   600
193                 north indian, chinese, continental                  1000
654  desserts, north indian, south indian, chinese,...                   500

     aggregate_rating
656               3.5
414               2.7
72                4.2
193               4.0
654               3.4

In [138]:
import pickle
import pandas as pd

# Save the trained KNN model
with open('knn_model.pkl', 'wb') as model_file:
    pickle.dump(knn, model_file)

# Save the TF-IDF matrix and indices
with open('tfidf_matrix.pkl', 'wb') as tfidf_file:
    pickle.dump(tfidf_matrix, tfidf_file)

with open('indices.pkl', 'wb') as indices_file:
    pickle.dump(indices, indices_file)

# Save the dataframe
df_new.to_pickle('df_new.pkl')